---
- name: Include user tasks.
  ansible.builtin.include_tasks: user.yml

- name: Ensure volume directories exist for gitea.
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
    owner: "{{ gitea_uid }}"
    group: "{{ gitea_gid }}"
  loop:
    - /srv/gitea/postgres
    - /srv/gitea/data
    - /srv/gitea/config

- name: Create Podman Network for gitea.
  containers.podman.podman_network:
    name: "{{ gitea_net_name }}"
    state: present

- name: Include db tasks.
  ansible.builtin.include_tasks: db.yml

- name: Include app tasks.
  ansible.builtin.include_tasks: app.yml
