---
## Volumes

- name: Ensure volume directories exist for gitea.
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  loop:
    - /srv/gitea/postgres
    - /srv/gitea/data
    - /srv/gitea/config

- name: Run tasks for user root.
  become: true
  block:
    - name: Create Podman Network for gitea.
      containers.podman.podman_network:
        name: "{{ gitea_net_name }}"
        state: present

    - name: Pull gitea-db image
      containers.podman.podman_image:
        name: "{{ gitea_db_image_name }}"
        tag: "{{ gitea_db_image_tag }}"

    - name: Run gitea-db container
      containers.podman.podman_container:
        name: gitea-db
        image: "{{ gitea_db_image_name }}:{{ gitea_db_image_tag }}"
        state: started
        recreate: true
        restart_policy: always
        network:
          - "{{ gitea_net_name }}"
        volumes:
          - "/srv/gitea/postgres:/var/lib/postgresql/data:Z"
        env:
          POSTGRES_USER: "{{ gitea_db_user }}"
          POSTGRES_PASSWORD: "{{ gitea_db_pass }}"
          POSTGRES_DB: "{{ gitea_db_name }}"
          TZ: "Asia/Taipei"

    - name: Pull gitea-app Image
      containers.podman.podman_image:
        name: "{{ gitea_app_image_name }}"
        tag: "{{ gitea_app_image_tag }}"
        state: present

    - name: Run gitea-app container
      containers.podman.podman_container:
        name: gitea-app
        image: "{{ gitea_app_image_name }}:{{ gitea_app_image_tag }}"
        state: started
        recreate: true
        restart_policy: always
        network:
          - "{{ gitea_net_name }}"
        volumes:
          - /srv/gitea/data:/var/lib/gitea:Z
          - /srv/gitea/config:/etc/gitea:Z
          - /etc/localtime:/etc/localtime:ro
        publish:
          - "{{ gitea_publish_http }}:3000"
          - "{{ gitea_publish_ssh }}:22"
        env:
          GITEA__database__DB_TYPE: postgres
          GITEA__database__HOST: "gitea-db:5432"
          GITEA__database__NAME: "{{ gitea_db_name }}"
          GITEA__database__USER: "{{ gitea_db_user }}"
          GITEA__database__PASSWD: "{{ gitea_db_pass }}"
