---
- name: Install gitea-shell template
  become: true
  ansible.builtin.template:
    src: templates/usr/local/bin/gitea-shell.j2
    dest: /usr/local/bin/gitea-shell
    mode: "0755"

- name: Create a user named git.
  become: true
  ansible.builtin.user:
    name: git
    state: present
    password: '!'
    comment: "Git Version Control"
    home: /home/git
    shell: /bin/bash
  register: user_data

- name: Enable linger for user git.
  become: true
  ansible.builtin.command:
    cmd: "loginctl enable-linger git"
  changed_when: true

- name: Override ssh settings for git user in /etc/ssh/sshd_config.
  become: true
  ansible.builtin.blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match User git
        AuthorizedKeysCommandUser git
        AuthorizedKeysCommand /usr/bin/podman exec -i gitea-app /usr/local/bin/gitea keys -c /etc/gitea/app.ini -u %u -t %t -k %k

- name: Set facts for UID and GID of git user.
  ansible.builtin.set_fact:
    gitea_uid: "{{ user_data.uid }}"
    gitea_gid: "{{ user_data.group }}"

## Volumes

- name: Ensure volume directories exist for gitea.
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
    owner: "{{ gitea_uid }}"
    group: "{{ gitea_gid }}"
  become: true
  loop:
    - /srv/gitea/postgres
    - /srv/gitea/data
    - /srv/gitea/config


- name: Run tasks for user git.
  become: true
  become_user: git
  block:
    - name: Create Podman Network for gitea.
      containers.podman.podman_network:
        name: "{{ gitea_net_name }}"
        state: present

    - name: Pull gitea-db image
      containers.podman.podman_image:
        name: "{{ gitea_db_image_name }}"
        tag: "{{ gitea_db_image_tag }}"

    - name: Run gitea-db container
      containers.podman.podman_container:
        name: gitea-db
        image: "{{ gitea_db_image_name }}:{{ gitea_db_image_tag }}"
        state: started
        recreate: true
        restart_policy: always
        network:
          - "{{ gitea_net_name }}"
        volumes:
          - "/srv/gitea/postgres:/var/lib/postgresql/data:Z"
        env:
          POSTGRES_USER: "{{ gitea_db_user }}"
          POSTGRES_PASSWORD: "{{ gitea_db_pass }}"
          POSTGRES_DB: "{{ gitea_db_name }}"
          TZ: "Asia/Taipei"

    - name: Pull gitea-app Image
      containers.podman.podman_image:
        name: "{{ gitea_app_image_name }}"
        tag: "{{ gitea_app_image_tag }}"
        state: present

    - name: Run gitea-app container
      containers.podman.podman_container:
        name: gitea-app
        image: "{{ gitea_app_image_name }}:{{ gitea_app_image_tag }}"
        state: started
        recreate: true
        user: "{{ gitea_uid }}"
        restart_policy: always
        network:
          - "{{ gitea_net_name }}"
        volumes:
          - /srv/gitea/data:/var/lib/gitea:Z
          - /srv/gitea/config:/etc/gitea:Z
          - /etc/localtime:/etc/localtime:ro
        publish:
          - "{{ gitea_publish_http }}:3000"
          - "{{ gitea_publish_ssh }}:2222"
        env:
          GITEA__database__DB_TYPE: postgres
          GITEA__database__HOST: "gitea-db:5432"
          GITEA__database__NAME: "{{ gitea_db_name }}"
          GITEA__database__USER: "{{ gitea_db_user }}"
          GITEA__database__PASSWD: "{{ gitea_db_pass }}"

- name: Set git user shell to gitea-shell.
  when: false
  become: true
  ansible.builtin.user:
    name: git
    state: present
    shell: /usr/local/bin/gitea-shell

- name: Restart sshd.
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted
